channels:
- conda-forge
dependencies:
- python=3.9.5
- pip
- pip:
  - mlflow
  - cffi==1.14.6
  - cloudpickle==2.0.0
  - configparser==5.2.0
  - pytorch-lightning==1.5.9
  - torch==1.10.1
  - torchvision==0.11.2
name: mlflow-env
